<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use backend\models\NoticeInfo;

/**
 * Site controller
 */
class SiteController extends Controller
{
   public $ranking=array();//点击前十
   public function init()
   {
       parent::init(); // TODO: Change the autogenerated stub
       Yii::$app->view->params['column']=Yii::$app->params['publicConfig']['column'];//栏目
       Yii::$app->view->params['siteName']=Yii::$app->params['publicConfig']['siteName'];//站点名字
       //实例化模型
       $noticeModel=NoticeInfo::find();
       //查询本页数据
       $list = $noticeModel->select(['notice_title','id','watch_number'])->offset(0)->orderBy('watch_number desc')
           ->limit(10)
           ->asArray()
           ->all();
       $this->ranking=$list;
   }

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error','test','index','list','home','listcolumn'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}
